# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    name: Build & Test (${{ matrix.ocaml }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ocaml: [ "5.1", "4.14" ]

    steps:
    # 1 ▸ Check out sources
    - uses: actions/checkout@v4

    # 2 ▸ Install OCaml + opam, with build-cache enabled
    - uses: avsm/setup-ocaml@v2
      with:
        ocaml-compiler: ${{ matrix.ocaml }}
        dune-cache: true
        opam-depext: false
        opam-repositories: |
          default

    # (If Menhir needs external libs on your distribution)
    - run: sudo apt-get update && sudo apt-get install -y m4

    # 3 ▸ Install project dependencies (+test deps)
    - run: opam install . --deps-only --with-test --yes

    # 4 ▸ Build & run unit tests
    - run: dune build
    - run: dune runtest

    # 5 ▸ Optional: enforce formatting
    - run: opam install ocamlformat --yes
    - run: dune build @fmt --auto-promote
    - run: git diff --exit-code
